# Generated by Django 3.2.8 on 2021-11-05 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=200)),
                ('contact_num', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DN', 'DONATION'), ('LT', 'Loan Taken'), ('LR', 'Loan Returned')], default='DN', max_length=2)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funds.participant')),
            ],
        ),
    ]
