# Generated by Django 3.2.8 on 2021-11-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='contact_num',
            field=models.CharField(max_length=200),
        ),
    ]
