# Generated by Django 3.2.8 on 2021-11-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_alter_participant_contact_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Donation', 'Donation'), ('Loan Taken', 'Loan Taken'), ('Loan Returned', 'Loan Returned')], default='Donation', max_length=20),
        ),
    ]
