# Generated by Django 3.2.8 on 2021-11-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0003_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('DN', 'Donation'), ('LT', 'Loan Taken'), ('LR', 'Loan Returned')], default='DN', max_length=2),
        ),
    ]
