# Generated by Django 3.2.8 on 2021-11-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='p_type',
            field=models.CharField(choices=[('DONOR', 'Donor'), ('LOANER', 'Loaner')], default='DONOR', max_length=6),
        ),
    ]
