# Generated by Django 3.2.8 on 2021-11-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0006_alter_participant_p_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
