# Generated by Django 3.2.8 on 2021-11-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0007_alter_participant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='account_num',
            field=models.IntegerField(default=0, editable=False, verbose_name='Account Number'),
        ),
    ]
